{{- range $service := (list "api") }}
{{- $serviceValues := index $.Values.backend $service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "DOChart.componentname" (list $ (printf "%s-service" $service)) }}
  labels: {{- include "DOChart.labels.backend.api" (list $ (printf "%s-service" $service)) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - targetPort: {{ printf "%s-port" $service }}
      protocol: TCP
      name: {{ printf "%s-port" $service }}
      port: {{ $serviceValues.port }}
  selector: {{- include "DOChart.labels.backend.api" (list $ (printf "%s-service" $service)) | nindent 4 }}
---
{{ end }}
