// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	SpatialRefSys string
	Tickers       string
	Users         string
}{
	SpatialRefSys: "spatial_ref_sys",
	Tickers:       "tickers",
	Users:         "users",
}
